services:
  nginx:
    image: nginx:alpine
    container_name: quiz_nginx_lb
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./web:/app/web
    expose:
      - "8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=quiz_system
      - JWT_SECRET=super-secret-college-quiz-jwt-key-2026
      - JWT_EXPIRY_MINUTES=45
      - ADMIN_PIN=admin123
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: quiz_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
